// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/auth/v1/notification_service.proto

package authv1

import (
	v1 "gitlab.crja72.ru/golang/2025/spring/course/projects/go9/gogetnote/pkg/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип уведомления
type NotificationType int32

const (
	// Неизвестный тип уведомления (значение по умолчанию)
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	// Системное уведомление от приложения
	NotificationType_NOTIFICATION_TYPE_SYSTEM NotificationType = 1
	// Уведомление о предоставленном доступе к боксу
	NotificationType_NOTIFICATION_TYPE_BOX_ACCESS_GRANTED NotificationType = 2
	// Уведомление об изменении уровня доступа к боксу
	NotificationType_NOTIFICATION_TYPE_BOX_ACCESS_CHANGED NotificationType = 3
	// Уведомление об отзыве доступа к боксу
	NotificationType_NOTIFICATION_TYPE_BOX_ACCESS_REVOKED NotificationType = 4
	// Уведомление о приглашении к сотрудничеству над заметкой
	NotificationType_NOTIFICATION_TYPE_NOTE_COLLABORATION NotificationType = 5
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_SYSTEM",
		2: "NOTIFICATION_TYPE_BOX_ACCESS_GRANTED",
		3: "NOTIFICATION_TYPE_BOX_ACCESS_CHANGED",
		4: "NOTIFICATION_TYPE_BOX_ACCESS_REVOKED",
		5: "NOTIFICATION_TYPE_NOTE_COLLABORATION",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":        0,
		"NOTIFICATION_TYPE_SYSTEM":             1,
		"NOTIFICATION_TYPE_BOX_ACCESS_GRANTED": 2,
		"NOTIFICATION_TYPE_BOX_ACCESS_CHANGED": 3,
		"NOTIFICATION_TYPE_BOX_ACCESS_REVOKED": 4,
		"NOTIFICATION_TYPE_NOTE_COLLABORATION": 5,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_notification_service_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_api_auth_v1_notification_service_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{0}
}

// Статус уведомления
type NotificationStatus int32

const (
	// Неизвестный статус уведомления (значение по умолчанию)
	NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED NotificationStatus = 0
	// Непрочитанное уведомление
	NotificationStatus_NOTIFICATION_STATUS_UNREAD NotificationStatus = 1
	// Прочитанное уведомление
	NotificationStatus_NOTIFICATION_STATUS_READ NotificationStatus = 2
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNSPECIFIED",
		1: "NOTIFICATION_STATUS_UNREAD",
		2: "NOTIFICATION_STATUS_READ",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNSPECIFIED": 0,
		"NOTIFICATION_STATUS_UNREAD":      1,
		"NOTIFICATION_STATUS_READ":        2,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_notification_service_proto_enumTypes[1].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_api_auth_v1_notification_service_proto_enumTypes[1]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{1}
}

// Тип события
type NotificationEvent_EventType int32

const (
	// Неизвестный тип события
	NotificationEvent_EVENT_TYPE_UNSPECIFIED NotificationEvent_EventType = 0
	// Новое уведомление
	NotificationEvent_EVENT_TYPE_NEW NotificationEvent_EventType = 1
	// Обновление существующего уведомления
	NotificationEvent_EVENT_TYPE_UPDATED NotificationEvent_EventType = 2
	// Удаление уведомления
	NotificationEvent_EVENT_TYPE_DELETED NotificationEvent_EventType = 3
)

// Enum value maps for NotificationEvent_EventType.
var (
	NotificationEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_NEW",
		2: "EVENT_TYPE_UPDATED",
		3: "EVENT_TYPE_DELETED",
	}
	NotificationEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_NEW":         1,
		"EVENT_TYPE_UPDATED":     2,
		"EVENT_TYPE_DELETED":     3,
	}
)

func (x NotificationEvent_EventType) Enum() *NotificationEvent_EventType {
	p := new(NotificationEvent_EventType)
	*p = x
	return p
}

func (x NotificationEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_auth_v1_notification_service_proto_enumTypes[2].Descriptor()
}

func (NotificationEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_auth_v1_notification_service_proto_enumTypes[2]
}

func (x NotificationEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationEvent_EventType.Descriptor instead.
func (NotificationEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{7, 0}
}

// Запрос на получение списка уведомлений
type ListNotificationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Параметры пагинации
	Pagination *v1.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Фильтр по статусу уведомлений (опционально)
	Status *NotificationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=auth.v1.NotificationStatus,oneof" json:"status,omitempty"`
	// Фильтр по типу уведомлений (опционально)
	Type *NotificationType `protobuf:"varint,3,opt,name=type,proto3,enum=auth.v1.NotificationType,oneof" json:"type,omitempty"`
	// Параметры сортировки
	Sort          *v1.SortRequest `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotificationsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotificationsRequest) GetStatus() NotificationStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetType() NotificationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetSort() *v1.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

// Ответ со списком уведомлений
type ListNotificationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список уведомлений
	Notifications []*NotificationMessage `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	// Метаданные пагинации
	Pagination *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Количество непрочитанных уведомлений
	UnreadCount   int32 `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsResponse) GetNotifications() []*NotificationMessage {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotificationsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// Структура уведомления
type NotificationMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор уведомления
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// Тип уведомления
	Type NotificationType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.v1.NotificationType" json:"type,omitempty"`
	// Заголовок уведомления
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Текст уведомления
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Статус уведомления
	Status NotificationStatus `protobuf:"varint,5,opt,name=status,proto3,enum=auth.v1.NotificationStatus" json:"status,omitempty"`
	// Время создания уведомления
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Время последнего обновления уведомления
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Дополнительные данные в зависимости от типа уведомления
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMessage) Reset() {
	*x = NotificationMessage{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMessage) ProtoMessage() {}

func (x *NotificationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMessage.ProtoReflect.Descriptor instead.
func (*NotificationMessage) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationMessage) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationMessage) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationMessage) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *NotificationMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationMessage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *NotificationMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Запрос на обновление статуса уведомления
type UpdateNotificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID уведомления для обновления
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// Новый статус уведомления
	Status        NotificationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=auth.v1.NotificationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationRequest) Reset() {
	*x = UpdateNotificationRequest{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationRequest) ProtoMessage() {}

func (x *UpdateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *UpdateNotificationRequest) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

// Ответ с обновленным уведомлением
type NotificationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Обновленное уведомление
	Notification  *NotificationMessage `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationResponse) GetNotification() *NotificationMessage {
	if x != nil {
		return x.Notification
	}
	return nil
}

// Запрос на пакетное обновление статусов уведомлений
type BatchUpdateNotificationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список ID уведомлений для обновления
	NotificationIds []string `protobuf:"bytes,1,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"`
	// Новый статус для всех указанных уведомлений
	Status NotificationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=auth.v1.NotificationStatus" json:"status,omitempty"`
	// Если true, то все уведомления пользователя будут обновлены
	UpdateAll     bool `protobuf:"varint,3,opt,name=update_all,json=updateAll,proto3" json:"update_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateNotificationsRequest) Reset() {
	*x = BatchUpdateNotificationsRequest{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateNotificationsRequest) ProtoMessage() {}

func (x *BatchUpdateNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateNotificationsRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchUpdateNotificationsRequest) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

func (x *BatchUpdateNotificationsRequest) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *BatchUpdateNotificationsRequest) GetUpdateAll() bool {
	if x != nil {
		return x.UpdateAll
	}
	return false
}

// Запрос на подписку на уведомления
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор пользователя, чьи уведомления нужно отслеживать
	// (Обычно извлекается из авторизационного токена)
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Событие уведомления для потоковой передачи
type NotificationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Тип события
	EventType NotificationEvent_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=auth.v1.NotificationEvent_EventType" json:"event_type,omitempty"`
	// Данные уведомления
	Notification  *NotificationMessage `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{7}
}

func (x *NotificationEvent) GetEventType() NotificationEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return NotificationEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *NotificationEvent) GetNotification() *NotificationMessage {
	if x != nil {
		return x.Notification
	}
	return nil
}

// Запрос на отправку уведомления пользователю (внутренний метод)
type SendNotificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID пользователя, которому отправляется уведомление
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Тип уведомления
	Type NotificationType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.v1.NotificationType" json:"type,omitempty"`
	// Заголовок уведомления
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Текст уведомления
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Дополнительные данные в зависимости от типа уведомления
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_notification_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_notification_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendNotificationRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendNotificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_auth_v1_notification_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_notification_service_proto_rawDesc = "" +
	"\n" +
	"&api/auth/v1/notification_service.proto\x12\aauth.v1\x1a api/google/api/annotations.proto\x1a#api/google/protobuf/timestamp.proto\x1a\x1fapi/google/protobuf/empty.proto\x1a\x1eapi/common/v1/pagination.proto\"\x86\x02\n" +
	"\x18ListNotificationsRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.auth.v1.NotificationStatusH\x00R\x06status\x88\x01\x01\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.auth.v1.NotificationTypeH\x01R\x04type\x88\x01\x01\x12*\n" +
	"\x04sort\x18\x04 \x01(\v2\x16.common.v1.SortRequestR\x04sortB\t\n" +
	"\a_statusB\a\n" +
	"\x05_type\"\xc1\x01\n" +
	"\x19ListNotificationsResponse\x12B\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1c.auth.v1.NotificationMessageR\rnotifications\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\x12!\n" +
	"\funread_count\x18\x03 \x01(\x05R\vunreadCount\"\xcd\x03\n" +
	"\x13NotificationMessage\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.auth.v1.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.auth.v1.NotificationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12F\n" +
	"\bmetadata\x18\b \x03(\v2*.auth.v1.NotificationMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x19UpdateNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.auth.v1.NotificationStatusR\x06status\"X\n" +
	"\x14NotificationResponse\x12@\n" +
	"\fnotification\x18\x01 \x01(\v2\x1c.auth.v1.NotificationMessageR\fnotification\"\xa0\x01\n" +
	"\x1fBatchUpdateNotificationsRequest\x12)\n" +
	"\x10notification_ids\x18\x01 \x03(\tR\x0fnotificationIds\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.auth.v1.NotificationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"update_all\x18\x03 \x01(\bR\tupdateAll\"+\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x87\x02\n" +
	"\x11NotificationEvent\x12C\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2$.auth.v1.NotificationEvent.EventTypeR\teventType\x12@\n" +
	"\fnotification\x18\x02 \x01(\v2\x1c.auth.v1.NotificationMessageR\fnotification\"k\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_TYPE_NEW\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_UPDATED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x03\"\x9a\x02\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.auth.v1.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..auth.v1.SendNotificationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xfb\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18NOTIFICATION_TYPE_SYSTEM\x10\x01\x12(\n" +
	"$NOTIFICATION_TYPE_BOX_ACCESS_GRANTED\x10\x02\x12(\n" +
	"$NOTIFICATION_TYPE_BOX_ACCESS_CHANGED\x10\x03\x12(\n" +
	"$NOTIFICATION_TYPE_BOX_ACCESS_REVOKED\x10\x04\x12(\n" +
	"$NOTIFICATION_TYPE_NOTE_COLLABORATION\x10\x05*w\n" +
	"\x12NotificationStatus\x12#\n" +
	"\x1fNOTIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_UNREAD\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_READ\x10\x022\xbd\x04\n" +
	"\x13NotificationService\x12u\n" +
	"\x11ListNotifications\x12!.auth.v1.ListNotificationsRequest\x1a\".auth.v1.ListNotificationsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/notifications\x12\x87\x01\n" +
	"\x12UpdateNotification\x12\".auth.v1.UpdateNotificationRequest\x1a\x1d.auth.v1.NotificationResponse\".\x82\xd3\xe4\x93\x02(:\x01*2#/v1/notifications/{notification_id}\x12z\n" +
	"\x18BatchUpdateNotifications\x12(.auth.v1.BatchUpdateNotificationsRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/v1/notifications\x12Y\n" +
	"\x1cSubscribeToUserNotifications\x12\x19.auth.v1.SubscribeRequest\x1a\x1a.auth.v1.NotificationEvent\"\x000\x01\x12N\n" +
	"\x10SendNotification\x12 .auth.v1.SendNotificationRequest\x1a\x16.google.protobuf.Empty\"\x00BZZXgitlab.crja72.ru/golang/2025/spring/course/projects/go9/gogetnote/pkg/api/auth/v1;authv1b\x06proto3"

var (
	file_api_auth_v1_notification_service_proto_rawDescOnce sync.Once
	file_api_auth_v1_notification_service_proto_rawDescData []byte
)

func file_api_auth_v1_notification_service_proto_rawDescGZIP() []byte {
	file_api_auth_v1_notification_service_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_notification_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_notification_service_proto_rawDesc), len(file_api_auth_v1_notification_service_proto_rawDesc)))
	})
	return file_api_auth_v1_notification_service_proto_rawDescData
}

var file_api_auth_v1_notification_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_auth_v1_notification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_auth_v1_notification_service_proto_goTypes = []any{
	(NotificationType)(0),                   // 0: auth.v1.NotificationType
	(NotificationStatus)(0),                 // 1: auth.v1.NotificationStatus
	(NotificationEvent_EventType)(0),        // 2: auth.v1.NotificationEvent.EventType
	(*ListNotificationsRequest)(nil),        // 3: auth.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),       // 4: auth.v1.ListNotificationsResponse
	(*NotificationMessage)(nil),             // 5: auth.v1.NotificationMessage
	(*UpdateNotificationRequest)(nil),       // 6: auth.v1.UpdateNotificationRequest
	(*NotificationResponse)(nil),            // 7: auth.v1.NotificationResponse
	(*BatchUpdateNotificationsRequest)(nil), // 8: auth.v1.BatchUpdateNotificationsRequest
	(*SubscribeRequest)(nil),                // 9: auth.v1.SubscribeRequest
	(*NotificationEvent)(nil),               // 10: auth.v1.NotificationEvent
	(*SendNotificationRequest)(nil),         // 11: auth.v1.SendNotificationRequest
	nil,                                     // 12: auth.v1.NotificationMessage.MetadataEntry
	nil,                                     // 13: auth.v1.SendNotificationRequest.MetadataEntry
	(*v1.PaginationRequest)(nil),            // 14: common.v1.PaginationRequest
	(*v1.SortRequest)(nil),                  // 15: common.v1.SortRequest
	(*v1.PaginationResponse)(nil),           // 16: common.v1.PaginationResponse
	(*timestamppb.Timestamp)(nil),           // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 18: google.protobuf.Empty
}
var file_api_auth_v1_notification_service_proto_depIdxs = []int32{
	14, // 0: auth.v1.ListNotificationsRequest.pagination:type_name -> common.v1.PaginationRequest
	1,  // 1: auth.v1.ListNotificationsRequest.status:type_name -> auth.v1.NotificationStatus
	0,  // 2: auth.v1.ListNotificationsRequest.type:type_name -> auth.v1.NotificationType
	15, // 3: auth.v1.ListNotificationsRequest.sort:type_name -> common.v1.SortRequest
	5,  // 4: auth.v1.ListNotificationsResponse.notifications:type_name -> auth.v1.NotificationMessage
	16, // 5: auth.v1.ListNotificationsResponse.pagination:type_name -> common.v1.PaginationResponse
	0,  // 6: auth.v1.NotificationMessage.type:type_name -> auth.v1.NotificationType
	1,  // 7: auth.v1.NotificationMessage.status:type_name -> auth.v1.NotificationStatus
	17, // 8: auth.v1.NotificationMessage.created_at:type_name -> google.protobuf.Timestamp
	17, // 9: auth.v1.NotificationMessage.updated_at:type_name -> google.protobuf.Timestamp
	12, // 10: auth.v1.NotificationMessage.metadata:type_name -> auth.v1.NotificationMessage.MetadataEntry
	1,  // 11: auth.v1.UpdateNotificationRequest.status:type_name -> auth.v1.NotificationStatus
	5,  // 12: auth.v1.NotificationResponse.notification:type_name -> auth.v1.NotificationMessage
	1,  // 13: auth.v1.BatchUpdateNotificationsRequest.status:type_name -> auth.v1.NotificationStatus
	2,  // 14: auth.v1.NotificationEvent.event_type:type_name -> auth.v1.NotificationEvent.EventType
	5,  // 15: auth.v1.NotificationEvent.notification:type_name -> auth.v1.NotificationMessage
	0,  // 16: auth.v1.SendNotificationRequest.type:type_name -> auth.v1.NotificationType
	13, // 17: auth.v1.SendNotificationRequest.metadata:type_name -> auth.v1.SendNotificationRequest.MetadataEntry
	3,  // 18: auth.v1.NotificationService.ListNotifications:input_type -> auth.v1.ListNotificationsRequest
	6,  // 19: auth.v1.NotificationService.UpdateNotification:input_type -> auth.v1.UpdateNotificationRequest
	8,  // 20: auth.v1.NotificationService.BatchUpdateNotifications:input_type -> auth.v1.BatchUpdateNotificationsRequest
	9,  // 21: auth.v1.NotificationService.SubscribeToUserNotifications:input_type -> auth.v1.SubscribeRequest
	11, // 22: auth.v1.NotificationService.SendNotification:input_type -> auth.v1.SendNotificationRequest
	4,  // 23: auth.v1.NotificationService.ListNotifications:output_type -> auth.v1.ListNotificationsResponse
	7,  // 24: auth.v1.NotificationService.UpdateNotification:output_type -> auth.v1.NotificationResponse
	18, // 25: auth.v1.NotificationService.BatchUpdateNotifications:output_type -> google.protobuf.Empty
	10, // 26: auth.v1.NotificationService.SubscribeToUserNotifications:output_type -> auth.v1.NotificationEvent
	18, // 27: auth.v1.NotificationService.SendNotification:output_type -> google.protobuf.Empty
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_auth_v1_notification_service_proto_init() }
func file_api_auth_v1_notification_service_proto_init() {
	if File_api_auth_v1_notification_service_proto != nil {
		return
	}
	file_api_auth_v1_notification_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_notification_service_proto_rawDesc), len(file_api_auth_v1_notification_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_notification_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_notification_service_proto_depIdxs,
		EnumInfos:         file_api_auth_v1_notification_service_proto_enumTypes,
		MessageInfos:      file_api_auth_v1_notification_service_proto_msgTypes,
	}.Build()
	File_api_auth_v1_notification_service_proto = out.File
	file_api_auth_v1_notification_service_proto_goTypes = nil
	file_api_auth_v1_notification_service_proto_depIdxs = nil
}
