// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/common/v1/errors.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorResponse определяет стандартный формат ответа с ошибкой
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP статус-код (например, 400, 401, 403, 404, 422, 500)
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Код ошибки для программной обработки
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Человекочитаемое сообщение об ошибке
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_api_common_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ValidationError представляет ошибку валидации конкретного поля
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя поля с ошибкой
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Сообщение об ошибке
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_api_common_v1_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_api_common_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_common_v1_errors_proto protoreflect.FileDescriptor

const file_api_common_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/common/v1/errors.proto\x12\tcommon.v1\"U\n" +
	"\rErrorResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"A\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB^Z\\gitlab.crja72.ru/golang/2025/spring/course/projects/go9/gogetnote/pkg/api/common/v1;commonv1b\x06proto3"

var (
	file_api_common_v1_errors_proto_rawDescOnce sync.Once
	file_api_common_v1_errors_proto_rawDescData []byte
)

func file_api_common_v1_errors_proto_rawDescGZIP() []byte {
	file_api_common_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_common_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_errors_proto_rawDesc), len(file_api_common_v1_errors_proto_rawDesc)))
	})
	return file_api_common_v1_errors_proto_rawDescData
}

var file_api_common_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_common_v1_errors_proto_goTypes = []any{
	(*ErrorResponse)(nil),   // 0: common.v1.ErrorResponse
	(*ValidationError)(nil), // 1: common.v1.ValidationError
}
var file_api_common_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_common_v1_errors_proto_init() }
func file_api_common_v1_errors_proto_init() {
	if File_api_common_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_errors_proto_rawDesc), len(file_api_common_v1_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_common_v1_errors_proto_depIdxs,
		MessageInfos:      file_api_common_v1_errors_proto_msgTypes,
	}.Build()
	File_api_common_v1_errors_proto = out.File
	file_api_common_v1_errors_proto_goTypes = nil
	file_api_common_v1_errors_proto_depIdxs = nil
}
