// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/common/v1/metadata.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип значения поля
type UserDefinedField_FieldType int32

const (
	// Неизвестный тип (значение по умолчанию)
	UserDefinedField_FIELD_TYPE_UNSPECIFIED UserDefinedField_FieldType = 0
	// Строковое поле
	UserDefinedField_FIELD_TYPE_STRING UserDefinedField_FieldType = 1
	// Числовое поле
	UserDefinedField_FIELD_TYPE_NUMBER UserDefinedField_FieldType = 2
	// Логическое поле (истина/ложь)
	UserDefinedField_FIELD_TYPE_BOOLEAN UserDefinedField_FieldType = 3
	// Поле даты/времени
	UserDefinedField_FIELD_TYPE_DATETIME UserDefinedField_FieldType = 4
	// Поле с выбором из списка
	UserDefinedField_FIELD_TYPE_ENUM UserDefinedField_FieldType = 5
)

// Enum value maps for UserDefinedField_FieldType.
var (
	UserDefinedField_FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_STRING",
		2: "FIELD_TYPE_NUMBER",
		3: "FIELD_TYPE_BOOLEAN",
		4: "FIELD_TYPE_DATETIME",
		5: "FIELD_TYPE_ENUM",
	}
	UserDefinedField_FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_STRING":      1,
		"FIELD_TYPE_NUMBER":      2,
		"FIELD_TYPE_BOOLEAN":     3,
		"FIELD_TYPE_DATETIME":    4,
		"FIELD_TYPE_ENUM":        5,
	}
)

func (x UserDefinedField_FieldType) Enum() *UserDefinedField_FieldType {
	p := new(UserDefinedField_FieldType)
	*p = x
	return p
}

func (x UserDefinedField_FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserDefinedField_FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_metadata_proto_enumTypes[0].Descriptor()
}

func (UserDefinedField_FieldType) Type() protoreflect.EnumType {
	return &file_api_common_v1_metadata_proto_enumTypes[0]
}

func (x UserDefinedField_FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserDefinedField_FieldType.Descriptor instead.
func (UserDefinedField_FieldType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{4, 0}
}

// Тип активности
type ActivityRecord_ActivityType int32

const (
	// Неизвестный тип активности (значение по умолчанию)
	ActivityRecord_ACTIVITY_TYPE_UNSPECIFIED ActivityRecord_ActivityType = 0
	// Создание
	ActivityRecord_ACTIVITY_TYPE_CREATE ActivityRecord_ActivityType = 1
	// Изменение
	ActivityRecord_ACTIVITY_TYPE_UPDATE ActivityRecord_ActivityType = 2
	// Удаление
	ActivityRecord_ACTIVITY_TYPE_DELETE ActivityRecord_ActivityType = 3
	// Перемещение
	ActivityRecord_ACTIVITY_TYPE_MOVE ActivityRecord_ActivityType = 4
	// Совместный доступ
	ActivityRecord_ACTIVITY_TYPE_SHARE ActivityRecord_ActivityType = 5
	// Экспорт
	ActivityRecord_ACTIVITY_TYPE_EXPORT ActivityRecord_ActivityType = 6
	// Импорт
	ActivityRecord_ACTIVITY_TYPE_IMPORT ActivityRecord_ActivityType = 7
)

// Enum value maps for ActivityRecord_ActivityType.
var (
	ActivityRecord_ActivityType_name = map[int32]string{
		0: "ACTIVITY_TYPE_UNSPECIFIED",
		1: "ACTIVITY_TYPE_CREATE",
		2: "ACTIVITY_TYPE_UPDATE",
		3: "ACTIVITY_TYPE_DELETE",
		4: "ACTIVITY_TYPE_MOVE",
		5: "ACTIVITY_TYPE_SHARE",
		6: "ACTIVITY_TYPE_EXPORT",
		7: "ACTIVITY_TYPE_IMPORT",
	}
	ActivityRecord_ActivityType_value = map[string]int32{
		"ACTIVITY_TYPE_UNSPECIFIED": 0,
		"ACTIVITY_TYPE_CREATE":      1,
		"ACTIVITY_TYPE_UPDATE":      2,
		"ACTIVITY_TYPE_DELETE":      3,
		"ACTIVITY_TYPE_MOVE":        4,
		"ACTIVITY_TYPE_SHARE":       5,
		"ACTIVITY_TYPE_EXPORT":      6,
		"ACTIVITY_TYPE_IMPORT":      7,
	}
)

func (x ActivityRecord_ActivityType) Enum() *ActivityRecord_ActivityType {
	p := new(ActivityRecord_ActivityType)
	*p = x
	return p
}

func (x ActivityRecord_ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityRecord_ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_metadata_proto_enumTypes[1].Descriptor()
}

func (ActivityRecord_ActivityType) Type() protoreflect.EnumType {
	return &file_api_common_v1_metadata_proto_enumTypes[1]
}

func (x ActivityRecord_ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityRecord_ActivityType.Descriptor instead.
func (ActivityRecord_ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{5, 0}
}

// Состояние напоминания
type ReminderMetadata_ReminderState int32

const (
	// Неизвестное состояние (значение по умолчанию)
	ReminderMetadata_REMINDER_STATE_UNSPECIFIED ReminderMetadata_ReminderState = 0
	// Активное напоминание
	ReminderMetadata_REMINDER_STATE_ACTIVE ReminderMetadata_ReminderState = 1
	// Выполненное напоминание
	ReminderMetadata_REMINDER_STATE_COMPLETED ReminderMetadata_ReminderState = 2
	// Отмененное напоминание
	ReminderMetadata_REMINDER_STATE_CANCELLED ReminderMetadata_ReminderState = 3
)

// Enum value maps for ReminderMetadata_ReminderState.
var (
	ReminderMetadata_ReminderState_name = map[int32]string{
		0: "REMINDER_STATE_UNSPECIFIED",
		1: "REMINDER_STATE_ACTIVE",
		2: "REMINDER_STATE_COMPLETED",
		3: "REMINDER_STATE_CANCELLED",
	}
	ReminderMetadata_ReminderState_value = map[string]int32{
		"REMINDER_STATE_UNSPECIFIED": 0,
		"REMINDER_STATE_ACTIVE":      1,
		"REMINDER_STATE_COMPLETED":   2,
		"REMINDER_STATE_CANCELLED":   3,
	}
)

func (x ReminderMetadata_ReminderState) Enum() *ReminderMetadata_ReminderState {
	p := new(ReminderMetadata_ReminderState)
	*p = x
	return p
}

func (x ReminderMetadata_ReminderState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReminderMetadata_ReminderState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_metadata_proto_enumTypes[2].Descriptor()
}

func (ReminderMetadata_ReminderState) Type() protoreflect.EnumType {
	return &file_api_common_v1_metadata_proto_enumTypes[2]
}

func (x ReminderMetadata_ReminderState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReminderMetadata_ReminderState.Descriptor instead.
func (ReminderMetadata_ReminderState) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{7, 0}
}

// Повторение напоминания
type ReminderMetadata_RepeatInterval int32

const (
	// Без повторения (значение по умолчанию)
	ReminderMetadata_REPEAT_INTERVAL_NONE ReminderMetadata_RepeatInterval = 0
	// Ежедневное повторение
	ReminderMetadata_REPEAT_INTERVAL_DAILY ReminderMetadata_RepeatInterval = 1
	// Еженедельное повторение
	ReminderMetadata_REPEAT_INTERVAL_WEEKLY ReminderMetadata_RepeatInterval = 2
	// Ежемесячное повторение
	ReminderMetadata_REPEAT_INTERVAL_MONTHLY ReminderMetadata_RepeatInterval = 3
	// Ежегодное повторение
	ReminderMetadata_REPEAT_INTERVAL_YEARLY ReminderMetadata_RepeatInterval = 4
	// Пользовательский интервал
	ReminderMetadata_REPEAT_INTERVAL_CUSTOM ReminderMetadata_RepeatInterval = 5
)

// Enum value maps for ReminderMetadata_RepeatInterval.
var (
	ReminderMetadata_RepeatInterval_name = map[int32]string{
		0: "REPEAT_INTERVAL_NONE",
		1: "REPEAT_INTERVAL_DAILY",
		2: "REPEAT_INTERVAL_WEEKLY",
		3: "REPEAT_INTERVAL_MONTHLY",
		4: "REPEAT_INTERVAL_YEARLY",
		5: "REPEAT_INTERVAL_CUSTOM",
	}
	ReminderMetadata_RepeatInterval_value = map[string]int32{
		"REPEAT_INTERVAL_NONE":    0,
		"REPEAT_INTERVAL_DAILY":   1,
		"REPEAT_INTERVAL_WEEKLY":  2,
		"REPEAT_INTERVAL_MONTHLY": 3,
		"REPEAT_INTERVAL_YEARLY":  4,
		"REPEAT_INTERVAL_CUSTOM":  5,
	}
)

func (x ReminderMetadata_RepeatInterval) Enum() *ReminderMetadata_RepeatInterval {
	p := new(ReminderMetadata_RepeatInterval)
	*p = x
	return p
}

func (x ReminderMetadata_RepeatInterval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReminderMetadata_RepeatInterval) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_metadata_proto_enumTypes[3].Descriptor()
}

func (ReminderMetadata_RepeatInterval) Type() protoreflect.EnumType {
	return &file_api_common_v1_metadata_proto_enumTypes[3]
}

func (x ReminderMetadata_RepeatInterval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReminderMetadata_RepeatInterval.Descriptor instead.
func (ReminderMetadata_RepeatInterval) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{7, 1}
}

// Metadata представляет общую структуру метаданных для различных объектов системы
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация о создании объекта
	CreationInfo *CreationInfo `protobuf:"bytes,1,opt,name=creation_info,json=creationInfo,proto3" json:"creation_info,omitempty"`
	// Информация о последнем изменении объекта
	ModificationInfo *ModificationInfo `protobuf:"bytes,2,opt,name=modification_info,json=modificationInfo,proto3" json:"modification_info,omitempty"`
	// Произвольные пары ключ-значение для хранения дополнительных метаданных
	Attributes map[string]string `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Список тегов, связанных с объектом
	Tags []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	// Цветовая метка (HEX код, например "#4285F4" для синего)
	Color *string `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	// Приоритет объекта (от 0 до 100, где 100 - наивысший приоритет)
	Priority *int32 `protobuf:"varint,6,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	// Версия объекта (инкрементируется при каждом изменении)
	Version int64 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	// Расширенные метаданные в произвольных форматах
	ExtendedMetadata []*anypb.Any `protobuf:"bytes,8,rep,name=extended_metadata,json=extendedMetadata,proto3" json:"extended_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_common_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetCreationInfo() *CreationInfo {
	if x != nil {
		return x.CreationInfo
	}
	return nil
}

func (x *Metadata) GetModificationInfo() *ModificationInfo {
	if x != nil {
		return x.ModificationInfo
	}
	return nil
}

func (x *Metadata) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Metadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Metadata) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *Metadata) GetPriority() int32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *Metadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Metadata) GetExtendedMetadata() []*anypb.Any {
	if x != nil {
		return x.ExtendedMetadata
	}
	return nil
}

// CreationInfo содержит информацию о создании объекта
type CreationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Время создания объекта
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ID пользователя, создавшего объект
	CreatedByUserId string `protobuf:"bytes,2,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	// Имя пользователя, создавшего объект (для отображения)
	CreatedByUsername string `protobuf:"bytes,3,opt,name=created_by_username,json=createdByUsername,proto3" json:"created_by_username,omitempty"`
	// IP адрес, с которого был создан объект
	SourceIp *string `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3,oneof" json:"source_ip,omitempty"`
	// Клиентское устройство или приложение, с которого был создан объект
	UserAgent     *string `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreationInfo) Reset() {
	*x = CreationInfo{}
	mi := &file_api_common_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreationInfo) ProtoMessage() {}

func (x *CreationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreationInfo.ProtoReflect.Descriptor instead.
func (*CreationInfo) Descriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *CreationInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreationInfo) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

func (x *CreationInfo) GetCreatedByUsername() string {
	if x != nil {
		return x.CreatedByUsername
	}
	return ""
}

func (x *CreationInfo) GetSourceIp() string {
	if x != nil && x.SourceIp != nil {
		return *x.SourceIp
	}
	return ""
}

func (x *CreationInfo) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

// ModificationInfo содержит информацию о последнем изменении объекта
type ModificationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Время последнего изменения объекта
	ModifiedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	// ID пользователя, последним изменившего объект
	ModifiedByUserId string `protobuf:"bytes,2,opt,name=modified_by_user_id,json=modifiedByUserId,proto3" json:"modified_by_user_id,omitempty"`
	// Имя пользователя, последним изменившего объект
	ModifiedByUsername string `protobuf:"bytes,3,opt,name=modified_by_username,json=modifiedByUsername,proto3" json:"modified_by_username,omitempty"`
	// IP адрес, с которого было выполнено последнее изменение
	SourceIp *string `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3,oneof" json:"source_ip,omitempty"`
	// Клиентское устройство или приложение, с которого было выполнено последнее изменение
	UserAgent *string `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`
	// Описание изменения
	ChangeDescription *string `protobuf:"bytes,6,opt,name=change_description,json=changeDescription,proto3,oneof" json:"change_description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModificationInfo) Reset() {
	*x = ModificationInfo{}
	mi := &file_api_common_v1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModificationInfo) ProtoMessage() {}

func (x *ModificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModificationInfo.ProtoReflect.Descriptor instead.
func (*ModificationInfo) Descriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *ModificationInfo) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *ModificationInfo) GetModifiedByUserId() string {
	if x != nil {
		return x.ModifiedByUserId
	}
	return ""
}

func (x *ModificationInfo) GetModifiedByUsername() string {
	if x != nil {
		return x.ModifiedByUsername
	}
	return ""
}

func (x *ModificationInfo) GetSourceIp() string {
	if x != nil && x.SourceIp != nil {
		return *x.SourceIp
	}
	return ""
}

func (x *ModificationInfo) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *ModificationInfo) GetChangeDescription() string {
	if x != nil && x.ChangeDescription != nil {
		return *x.ChangeDescription
	}
	return ""
}

// Tag представляет тег с дополнительной информацией
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя тега
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Цвет тега (HEX код)
	Color *string `protobuf:"bytes,2,opt,name=color,proto3,oneof" json:"color,omitempty"`
	// Описание тега
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Время создания тега
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_api_common_v1_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *Tag) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Tag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// UserDefinedField представляет пользовательское поле
type UserDefinedField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор поля
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Название поля
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Тип поля
	Type UserDefinedField_FieldType `protobuf:"varint,3,opt,name=type,proto3,enum=common.v1.UserDefinedField_FieldType" json:"type,omitempty"`
	// Значение поля
	//
	// Types that are valid to be assigned to Value:
	//
	//	*UserDefinedField_StringValue
	//	*UserDefinedField_NumberValue
	//	*UserDefinedField_BooleanValue
	//	*UserDefinedField_DatetimeValue
	//	*UserDefinedField_EnumValue
	Value isUserDefinedField_Value `protobuf_oneof:"value"`
	// Время создания пользовательского поля
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Время последнего обновления пользовательского поля
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDefinedField) Reset() {
	*x = UserDefinedField{}
	mi := &file_api_common_v1_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDefinedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDefinedField) ProtoMessage() {}

func (x *UserDefinedField) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDefinedField.ProtoReflect.Descriptor instead.
func (*UserDefinedField) Descriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *UserDefinedField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserDefinedField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDefinedField) GetType() UserDefinedField_FieldType {
	if x != nil {
		return x.Type
	}
	return UserDefinedField_FIELD_TYPE_UNSPECIFIED
}

func (x *UserDefinedField) GetValue() isUserDefinedField_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UserDefinedField) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*UserDefinedField_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *UserDefinedField) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*UserDefinedField_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *UserDefinedField) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*UserDefinedField_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *UserDefinedField) GetDatetimeValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*UserDefinedField_DatetimeValue); ok {
			return x.DatetimeValue
		}
	}
	return nil
}

func (x *UserDefinedField) GetEnumValue() string {
	if x != nil {
		if x, ok := x.Value.(*UserDefinedField_EnumValue); ok {
			return x.EnumValue
		}
	}
	return ""
}

func (x *UserDefinedField) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserDefinedField) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type isUserDefinedField_Value interface {
	isUserDefinedField_Value()
}

type UserDefinedField_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type UserDefinedField_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,5,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type UserDefinedField_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,6,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type UserDefinedField_DatetimeValue struct {
	DatetimeValue *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=datetime_value,json=datetimeValue,proto3,oneof"`
}

type UserDefinedField_EnumValue struct {
	EnumValue string `protobuf:"bytes,8,opt,name=enum_value,json=enumValue,proto3,oneof"`
}

func (*UserDefinedField_StringValue) isUserDefinedField_Value() {}

func (*UserDefinedField_NumberValue) isUserDefinedField_Value() {}

func (*UserDefinedField_BooleanValue) isUserDefinedField_Value() {}

func (*UserDefinedField_DatetimeValue) isUserDefinedField_Value() {}

func (*UserDefinedField_EnumValue) isUserDefinedField_Value() {}

// ActivityRecord представляет запись об активности в системе
type ActivityRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор записи
	RecordId string `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	// Тип активности
	ActivityType ActivityRecord_ActivityType `protobuf:"varint,2,opt,name=activity_type,json=activityType,proto3,enum=common.v1.ActivityRecord_ActivityType" json:"activity_type,omitempty"`
	// ID объекта, с которым связана активность
	ObjectId string `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// Тип объекта (например, "заметка", "бокс")
	ObjectType string `protobuf:"bytes,4,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// ID пользователя, выполнившего действие
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Время активности
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Описание активности
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	// Дополнительные параметры активности
	Parameters    map[string]string `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityRecord) Reset() {
	*x = ActivityRecord{}
	mi := &file_api_common_v1_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRecord) ProtoMessage() {}

func (x *ActivityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRecord.ProtoReflect.Descriptor instead.
func (*ActivityRecord) Descriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *ActivityRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ActivityRecord) GetActivityType() ActivityRecord_ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityRecord_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *ActivityRecord) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ActivityRecord) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ActivityRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivityRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ActivityRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityRecord) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Структура для добавления геоинформации к объектам
type GeoMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Широта в десятичных градусах
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Долгота в десятичных градусах
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Описание местоположения (например, адрес)
	LocationDescription *string `protobuf:"bytes,3,opt,name=location_description,json=locationDescription,proto3,oneof" json:"location_description,omitempty"`
	// Точность геоданных в метрах
	Accuracy      *float64 `protobuf:"fixed64,4,opt,name=accuracy,proto3,oneof" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoMetadata) Reset() {
	*x = GeoMetadata{}
	mi := &file_api_common_v1_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoMetadata) ProtoMessage() {}

func (x *GeoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoMetadata.ProtoReflect.Descriptor instead.
func (*GeoMetadata) Descriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *GeoMetadata) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoMetadata) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoMetadata) GetLocationDescription() string {
	if x != nil && x.LocationDescription != nil {
		return *x.LocationDescription
	}
	return ""
}

func (x *GeoMetadata) GetAccuracy() float64 {
	if x != nil && x.Accuracy != nil {
		return *x.Accuracy
	}
	return 0
}

// Структура для хранения настроек напоминаний
type ReminderMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Время напоминания
	RemindAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	// Состояние напоминания
	State ReminderMetadata_ReminderState `protobuf:"varint,2,opt,name=state,proto3,enum=common.v1.ReminderMetadata_ReminderState" json:"state,omitempty"`
	// Интервал повторения
	RepeatInterval ReminderMetadata_RepeatInterval `protobuf:"varint,3,opt,name=repeat_interval,json=repeatInterval,proto3,enum=common.v1.ReminderMetadata_RepeatInterval" json:"repeat_interval,omitempty"`
	// Пользовательский интервал в минутах (для REPEAT_INTERVAL_CUSTOM)
	CustomIntervalMinutes *int32 `protobuf:"varint,4,opt,name=custom_interval_minutes,json=customIntervalMinutes,proto3,oneof" json:"custom_interval_minutes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReminderMetadata) Reset() {
	*x = ReminderMetadata{}
	mi := &file_api_common_v1_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderMetadata) ProtoMessage() {}

func (x *ReminderMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderMetadata.ProtoReflect.Descriptor instead.
func (*ReminderMetadata) Descriptor() ([]byte, []int) {
	return file_api_common_v1_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *ReminderMetadata) GetRemindAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RemindAt
	}
	return nil
}

func (x *ReminderMetadata) GetState() ReminderMetadata_ReminderState {
	if x != nil {
		return x.State
	}
	return ReminderMetadata_REMINDER_STATE_UNSPECIFIED
}

func (x *ReminderMetadata) GetRepeatInterval() ReminderMetadata_RepeatInterval {
	if x != nil {
		return x.RepeatInterval
	}
	return ReminderMetadata_REPEAT_INTERVAL_NONE
}

func (x *ReminderMetadata) GetCustomIntervalMinutes() int32 {
	if x != nil && x.CustomIntervalMinutes != nil {
		return *x.CustomIntervalMinutes
	}
	return 0
}

var File_api_common_v1_metadata_proto protoreflect.FileDescriptor

const file_api_common_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1capi/common/v1/metadata.proto\x12\tcommon.v1\x1a#api/google/protobuf/timestamp.proto\x1a\x1dapi/google/protobuf/any.proto\"\xda\x03\n" +
	"\bMetadata\x12<\n" +
	"\rcreation_info\x18\x01 \x01(\v2\x17.common.v1.CreationInfoR\fcreationInfo\x12H\n" +
	"\x11modification_info\x18\x02 \x01(\v2\x1b.common.v1.ModificationInfoR\x10modificationInfo\x12C\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2#.common.v1.Metadata.AttributesEntryR\n" +
	"attributes\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x00R\x05color\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x06 \x01(\x05H\x01R\bpriority\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12A\n" +
	"\x11extended_metadata\x18\b \x03(\v2\x14.google.protobuf.AnyR\x10extendedMetadata\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_colorB\v\n" +
	"\t_priority\"\x89\x02\n" +
	"\fCreationInfo\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x12created_by_user_id\x18\x02 \x01(\tR\x0fcreatedByUserId\x12.\n" +
	"\x13created_by_username\x18\x03 \x01(\tR\x11createdByUsername\x12 \n" +
	"\tsource_ip\x18\x04 \x01(\tH\x00R\bsourceIp\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tH\x01R\tuserAgent\x88\x01\x01B\f\n" +
	"\n" +
	"_source_ipB\r\n" +
	"\v_user_agent\"\xde\x02\n" +
	"\x10ModificationInfo\x12;\n" +
	"\vmodified_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12-\n" +
	"\x13modified_by_user_id\x18\x02 \x01(\tR\x10modifiedByUserId\x120\n" +
	"\x14modified_by_username\x18\x03 \x01(\tR\x12modifiedByUsername\x12 \n" +
	"\tsource_ip\x18\x04 \x01(\tH\x00R\bsourceIp\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tH\x01R\tuserAgent\x88\x01\x01\x122\n" +
	"\x12change_description\x18\x06 \x01(\tH\x02R\x11changeDescription\x88\x01\x01B\f\n" +
	"\n" +
	"_source_ipB\r\n" +
	"\v_user_agentB\x15\n" +
	"\x13_change_description\"\xb0\x01\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x02 \x01(\tH\x00R\x05color\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\b\n" +
	"\x06_colorB\x0e\n" +
	"\f_description\"\xe5\x04\n" +
	"\x10UserDefinedField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\x04type\x18\x03 \x01(\x0e2%.common.v1.UserDefinedField.FieldTypeR\x04type\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x05 \x01(\x01H\x00R\vnumberValue\x12%\n" +
	"\rboolean_value\x18\x06 \x01(\bH\x00R\fbooleanValue\x12C\n" +
	"\x0edatetime_value\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rdatetimeValue\x12\x1f\n" +
	"\n" +
	"enum_value\x18\b \x01(\tH\x00R\tenumValue\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FIELD_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11FIELD_TYPE_NUMBER\x10\x02\x12\x16\n" +
	"\x12FIELD_TYPE_BOOLEAN\x10\x03\x12\x17\n" +
	"\x13FIELD_TYPE_DATETIME\x10\x04\x12\x13\n" +
	"\x0fFIELD_TYPE_ENUM\x10\x05B\a\n" +
	"\x05value\"\x9a\x05\n" +
	"\x0eActivityRecord\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12K\n" +
	"\ractivity_type\x18\x02 \x01(\x0e2&.common.v1.ActivityRecord.ActivityTypeR\factivityType\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vobject_type\x18\x04 \x01(\tR\n" +
	"objectType\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12I\n" +
	"\n" +
	"parameters\x18\b \x03(\v2).common.v1.ActivityRecord.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\fActivityType\x12\x1d\n" +
	"\x19ACTIVITY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACTIVITY_TYPE_CREATE\x10\x01\x12\x18\n" +
	"\x14ACTIVITY_TYPE_UPDATE\x10\x02\x12\x18\n" +
	"\x14ACTIVITY_TYPE_DELETE\x10\x03\x12\x16\n" +
	"\x12ACTIVITY_TYPE_MOVE\x10\x04\x12\x17\n" +
	"\x13ACTIVITY_TYPE_SHARE\x10\x05\x12\x18\n" +
	"\x14ACTIVITY_TYPE_EXPORT\x10\x06\x12\x18\n" +
	"\x14ACTIVITY_TYPE_IMPORT\x10\a\"\xc6\x01\n" +
	"\vGeoMetadata\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x126\n" +
	"\x14location_description\x18\x03 \x01(\tH\x00R\x13locationDescription\x88\x01\x01\x12\x1f\n" +
	"\baccuracy\x18\x04 \x01(\x01H\x01R\baccuracy\x88\x01\x01B\x17\n" +
	"\x15_location_descriptionB\v\n" +
	"\t_accuracy\"\xfc\x04\n" +
	"\x10ReminderMetadata\x127\n" +
	"\tremind_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bremindAt\x12?\n" +
	"\x05state\x18\x02 \x01(\x0e2).common.v1.ReminderMetadata.ReminderStateR\x05state\x12S\n" +
	"\x0frepeat_interval\x18\x03 \x01(\x0e2*.common.v1.ReminderMetadata.RepeatIntervalR\x0erepeatInterval\x12;\n" +
	"\x17custom_interval_minutes\x18\x04 \x01(\x05H\x00R\x15customIntervalMinutes\x88\x01\x01\"\x86\x01\n" +
	"\rReminderState\x12\x1e\n" +
	"\x1aREMINDER_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REMINDER_STATE_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18REMINDER_STATE_COMPLETED\x10\x02\x12\x1c\n" +
	"\x18REMINDER_STATE_CANCELLED\x10\x03\"\xb6\x01\n" +
	"\x0eRepeatInterval\x12\x18\n" +
	"\x14REPEAT_INTERVAL_NONE\x10\x00\x12\x19\n" +
	"\x15REPEAT_INTERVAL_DAILY\x10\x01\x12\x1a\n" +
	"\x16REPEAT_INTERVAL_WEEKLY\x10\x02\x12\x1b\n" +
	"\x17REPEAT_INTERVAL_MONTHLY\x10\x03\x12\x1a\n" +
	"\x16REPEAT_INTERVAL_YEARLY\x10\x04\x12\x1a\n" +
	"\x16REPEAT_INTERVAL_CUSTOM\x10\x05B\x1a\n" +
	"\x18_custom_interval_minutesB^Z\\gitlab.crja72.ru/golang/2025/spring/course/projects/go9/gogetnote/pkg/api/common/v1;commonv1b\x06proto3"

var (
	file_api_common_v1_metadata_proto_rawDescOnce sync.Once
	file_api_common_v1_metadata_proto_rawDescData []byte
)

func file_api_common_v1_metadata_proto_rawDescGZIP() []byte {
	file_api_common_v1_metadata_proto_rawDescOnce.Do(func() {
		file_api_common_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_metadata_proto_rawDesc), len(file_api_common_v1_metadata_proto_rawDesc)))
	})
	return file_api_common_v1_metadata_proto_rawDescData
}

var file_api_common_v1_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_common_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_common_v1_metadata_proto_goTypes = []any{
	(UserDefinedField_FieldType)(0),      // 0: common.v1.UserDefinedField.FieldType
	(ActivityRecord_ActivityType)(0),     // 1: common.v1.ActivityRecord.ActivityType
	(ReminderMetadata_ReminderState)(0),  // 2: common.v1.ReminderMetadata.ReminderState
	(ReminderMetadata_RepeatInterval)(0), // 3: common.v1.ReminderMetadata.RepeatInterval
	(*Metadata)(nil),                     // 4: common.v1.Metadata
	(*CreationInfo)(nil),                 // 5: common.v1.CreationInfo
	(*ModificationInfo)(nil),             // 6: common.v1.ModificationInfo
	(*Tag)(nil),                          // 7: common.v1.Tag
	(*UserDefinedField)(nil),             // 8: common.v1.UserDefinedField
	(*ActivityRecord)(nil),               // 9: common.v1.ActivityRecord
	(*GeoMetadata)(nil),                  // 10: common.v1.GeoMetadata
	(*ReminderMetadata)(nil),             // 11: common.v1.ReminderMetadata
	nil,                                  // 12: common.v1.Metadata.AttributesEntry
	nil,                                  // 13: common.v1.ActivityRecord.ParametersEntry
	(*anypb.Any)(nil),                    // 14: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
}
var file_api_common_v1_metadata_proto_depIdxs = []int32{
	5,  // 0: common.v1.Metadata.creation_info:type_name -> common.v1.CreationInfo
	6,  // 1: common.v1.Metadata.modification_info:type_name -> common.v1.ModificationInfo
	12, // 2: common.v1.Metadata.attributes:type_name -> common.v1.Metadata.AttributesEntry
	14, // 3: common.v1.Metadata.extended_metadata:type_name -> google.protobuf.Any
	15, // 4: common.v1.CreationInfo.created_at:type_name -> google.protobuf.Timestamp
	15, // 5: common.v1.ModificationInfo.modified_at:type_name -> google.protobuf.Timestamp
	15, // 6: common.v1.Tag.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: common.v1.UserDefinedField.type:type_name -> common.v1.UserDefinedField.FieldType
	15, // 8: common.v1.UserDefinedField.datetime_value:type_name -> google.protobuf.Timestamp
	15, // 9: common.v1.UserDefinedField.created_at:type_name -> google.protobuf.Timestamp
	15, // 10: common.v1.UserDefinedField.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 11: common.v1.ActivityRecord.activity_type:type_name -> common.v1.ActivityRecord.ActivityType
	15, // 12: common.v1.ActivityRecord.timestamp:type_name -> google.protobuf.Timestamp
	13, // 13: common.v1.ActivityRecord.parameters:type_name -> common.v1.ActivityRecord.ParametersEntry
	15, // 14: common.v1.ReminderMetadata.remind_at:type_name -> google.protobuf.Timestamp
	2,  // 15: common.v1.ReminderMetadata.state:type_name -> common.v1.ReminderMetadata.ReminderState
	3,  // 16: common.v1.ReminderMetadata.repeat_interval:type_name -> common.v1.ReminderMetadata.RepeatInterval
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_common_v1_metadata_proto_init() }
func file_api_common_v1_metadata_proto_init() {
	if File_api_common_v1_metadata_proto != nil {
		return
	}
	file_api_common_v1_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_common_v1_metadata_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_common_v1_metadata_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_common_v1_metadata_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_common_v1_metadata_proto_msgTypes[4].OneofWrappers = []any{
		(*UserDefinedField_StringValue)(nil),
		(*UserDefinedField_NumberValue)(nil),
		(*UserDefinedField_BooleanValue)(nil),
		(*UserDefinedField_DatetimeValue)(nil),
		(*UserDefinedField_EnumValue)(nil),
	}
	file_api_common_v1_metadata_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_common_v1_metadata_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_metadata_proto_rawDesc), len(file_api_common_v1_metadata_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_metadata_proto_goTypes,
		DependencyIndexes: file_api_common_v1_metadata_proto_depIdxs,
		EnumInfos:         file_api_common_v1_metadata_proto_enumTypes,
		MessageInfos:      file_api_common_v1_metadata_proto_msgTypes,
	}.Build()
	File_api_common_v1_metadata_proto = out.File
	file_api_common_v1_metadata_proto_goTypes = nil
	file_api_common_v1_metadata_proto_depIdxs = nil
}
