services:
  postgres-auth:
    build:
      context: ../
      dockerfile: build/containers/docker/postgres.Dockerfile
    container_name: gogetnote-postgres-auth
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    ports:
      - "${AUTH_POSTGRES_PORT}:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    networks:
      - gogetnote-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  gogetnote-network:
    driver: bridge

volumes:
  postgres-auth-data:
