// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/notes/v1/box_service.proto

package notesv1

import (
	v1 "gitlab.crja72.ru/golang/2025/spring/course/projects/go9/gogetnote/pkg/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Уровень доступа к боксу
type AccessLevel int32

const (
	// Неизвестный уровень доступа (значение по умолчанию)
	AccessLevel_ACCESS_LEVEL_UNSPECIFIED AccessLevel = 0
	// Доступ только для чтения
	AccessLevel_ACCESS_LEVEL_READ AccessLevel = 1
	// Доступ для чтения и записи (редактирования)
	AccessLevel_ACCESS_LEVEL_WRITE AccessLevel = 2
	// Полный доступ, включая управление доступом других пользователей
	AccessLevel_ACCESS_LEVEL_ADMIN AccessLevel = 3
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "ACCESS_LEVEL_UNSPECIFIED",
		1: "ACCESS_LEVEL_READ",
		2: "ACCESS_LEVEL_WRITE",
		3: "ACCESS_LEVEL_ADMIN",
	}
	AccessLevel_value = map[string]int32{
		"ACCESS_LEVEL_UNSPECIFIED": 0,
		"ACCESS_LEVEL_READ":        1,
		"ACCESS_LEVEL_WRITE":       2,
		"ACCESS_LEVEL_ADMIN":       3,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notes_v1_box_service_proto_enumTypes[0].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_api_notes_v1_box_service_proto_enumTypes[0]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{0}
}

// Тип бокса
type BoxType int32

const (
	// Неизвестный тип бокса (значение по умолчанию)
	BoxType_BOX_TYPE_UNSPECIFIED BoxType = 0
	// Обычный бокс, созданный пользователем
	BoxType_BOX_TYPE_REGULAR BoxType = 1
	// Корневой бокс (автоматически создается для каждого пользователя)
	BoxType_BOX_TYPE_ROOT BoxType = 2
	// Системный бокс (например, Архив, Корзина)
	BoxType_BOX_TYPE_SYSTEM BoxType = 3
	// Совместный бокс (к которому имеют доступ несколько пользователей)
	BoxType_BOX_TYPE_SHARED BoxType = 4
)

// Enum value maps for BoxType.
var (
	BoxType_name = map[int32]string{
		0: "BOX_TYPE_UNSPECIFIED",
		1: "BOX_TYPE_REGULAR",
		2: "BOX_TYPE_ROOT",
		3: "BOX_TYPE_SYSTEM",
		4: "BOX_TYPE_SHARED",
	}
	BoxType_value = map[string]int32{
		"BOX_TYPE_UNSPECIFIED": 0,
		"BOX_TYPE_REGULAR":     1,
		"BOX_TYPE_ROOT":        2,
		"BOX_TYPE_SYSTEM":      3,
		"BOX_TYPE_SHARED":      4,
	}
)

func (x BoxType) Enum() *BoxType {
	p := new(BoxType)
	*p = x
	return p
}

func (x BoxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoxType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notes_v1_box_service_proto_enumTypes[1].Descriptor()
}

func (BoxType) Type() protoreflect.EnumType {
	return &file_api_notes_v1_box_service_proto_enumTypes[1]
}

func (x BoxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoxType.Descriptor instead.
func (BoxType) EnumDescriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{1}
}

// Запрос на создание бокса
type CreateBoxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название бокса
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Описание бокса (опционально)
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Цвет бокса (HEX код, например "#4285F4" для синего)
	Color *string `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	// Родительский бокс, в котором будет создан новый бокс (опционально)
	ParentBoxId *string `protobuf:"bytes,4,opt,name=parent_box_id,json=parentBoxId,proto3,oneof" json:"parent_box_id,omitempty"`
	// Иконка бокса (опционально)
	Icon *string `protobuf:"bytes,5,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	// Дополнительные метаданные бокса
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Пользовательские теги для бокса
	Tags []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// Приоритет бокса (от 0 до 100)
	Priority *int32 `protobuf:"varint,8,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	// Пользовательские поля
	UserDefinedFields []*v1.UserDefinedField `protobuf:"bytes,9,rep,name=user_defined_fields,json=userDefinedFields,proto3" json:"user_defined_fields,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateBoxRequest) Reset() {
	*x = CreateBoxRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoxRequest) ProtoMessage() {}

func (x *CreateBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoxRequest.ProtoReflect.Descriptor instead.
func (*CreateBoxRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBoxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBoxRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateBoxRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *CreateBoxRequest) GetParentBoxId() string {
	if x != nil && x.ParentBoxId != nil {
		return *x.ParentBoxId
	}
	return ""
}

func (x *CreateBoxRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *CreateBoxRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateBoxRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateBoxRequest) GetPriority() int32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *CreateBoxRequest) GetUserDefinedFields() []*v1.UserDefinedField {
	if x != nil {
		return x.UserDefinedFields
	}
	return nil
}

// Запрос на получение бокса
type GetBoxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса
	BoxId         string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoxRequest) Reset() {
	*x = GetBoxRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoxRequest) ProtoMessage() {}

func (x *GetBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoxRequest.ProtoReflect.Descriptor instead.
func (*GetBoxRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBoxRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

// Запрос на получение списка боксов
type ListBoxesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Параметры пагинации
	Pagination *v1.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Фильтр по типу боксов
	Type *BoxType `protobuf:"varint,2,opt,name=type,proto3,enum=notes.v1.BoxType,oneof" json:"type,omitempty"`
	// Фильтр по родительскому боксу (если указан, возвращаются только боксы внутри указанного)
	ParentBoxId *string `protobuf:"bytes,3,opt,name=parent_box_id,json=parentBoxId,proto3,oneof" json:"parent_box_id,omitempty"`
	// Включать ли в ответ совместные боксы
	IncludeShared bool `protobuf:"varint,4,opt,name=include_shared,json=includeShared,proto3" json:"include_shared,omitempty"`
	// Параметры сортировки
	Sort          *v1.SortRequest `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoxesRequest) Reset() {
	*x = ListBoxesRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoxesRequest) ProtoMessage() {}

func (x *ListBoxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoxesRequest.ProtoReflect.Descriptor instead.
func (*ListBoxesRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListBoxesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListBoxesRequest) GetType() BoxType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return BoxType_BOX_TYPE_UNSPECIFIED
}

func (x *ListBoxesRequest) GetParentBoxId() string {
	if x != nil && x.ParentBoxId != nil {
		return *x.ParentBoxId
	}
	return ""
}

func (x *ListBoxesRequest) GetIncludeShared() bool {
	if x != nil {
		return x.IncludeShared
	}
	return false
}

func (x *ListBoxesRequest) GetSort() *v1.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

// Ответ со списком боксов
type ListBoxesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список боксов
	Boxes []*Box `protobuf:"bytes,1,rep,name=boxes,proto3" json:"boxes,omitempty"`
	// Метаданные пагинации
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoxesResponse) Reset() {
	*x = ListBoxesResponse{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoxesResponse) ProtoMessage() {}

func (x *ListBoxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoxesResponse.ProtoReflect.Descriptor instead.
func (*ListBoxesResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListBoxesResponse) GetBoxes() []*Box {
	if x != nil {
		return x.Boxes
	}
	return nil
}

func (x *ListBoxesResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Запрос на обновление бокса
type UpdateBoxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса для обновления
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// Новое название бокса (опционально)
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Новое описание бокса (опционально)
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Новый цвет бокса (опционально)
	Color *string `protobuf:"bytes,4,opt,name=color,proto3,oneof" json:"color,omitempty"`
	// Новый родительский бокс (опционально)
	ParentBoxId *string `protobuf:"bytes,5,opt,name=parent_box_id,json=parentBoxId,proto3,oneof" json:"parent_box_id,omitempty"`
	// Новая иконка бокса (опционально)
	Icon *string `protobuf:"bytes,6,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	// Дополнительные метаданные бокса (опционально)
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoxRequest) Reset() {
	*x = UpdateBoxRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoxRequest) ProtoMessage() {}

func (x *UpdateBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoxRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoxRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBoxRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *UpdateBoxRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateBoxRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateBoxRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateBoxRequest) GetParentBoxId() string {
	if x != nil && x.ParentBoxId != nil {
		return *x.ParentBoxId
	}
	return ""
}

func (x *UpdateBoxRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *UpdateBoxRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Запрос на удаление бокса
type DeleteBoxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса для удаления
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// Удалять ли содержимое бокса (заметки) или только удалить бокс
	DeleteContents bool `protobuf:"varint,2,opt,name=delete_contents,json=deleteContents,proto3" json:"delete_contents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteBoxRequest) Reset() {
	*x = DeleteBoxRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoxRequest) ProtoMessage() {}

func (x *DeleteBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoxRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoxRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBoxRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *DeleteBoxRequest) GetDeleteContents() bool {
	if x != nil {
		return x.DeleteContents
	}
	return false
}

// Запрос на добавление заметки в бокс
type AddNoteToBoxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса, в который нужно добавить заметку
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// ID заметки, которую нужно добавить
	NoteId        string `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNoteToBoxRequest) Reset() {
	*x = AddNoteToBoxRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNoteToBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoteToBoxRequest) ProtoMessage() {}

func (x *AddNoteToBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoteToBoxRequest.ProtoReflect.Descriptor instead.
func (*AddNoteToBoxRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{6}
}

func (x *AddNoteToBoxRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *AddNoteToBoxRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

// Запрос на удаление заметки из бокса
type RemoveNoteFromBoxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса, из которого нужно удалить заметку
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// ID заметки, которую нужно удалить
	NoteId        string `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNoteFromBoxRequest) Reset() {
	*x = RemoveNoteFromBoxRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNoteFromBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNoteFromBoxRequest) ProtoMessage() {}

func (x *RemoveNoteFromBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNoteFromBoxRequest.ProtoReflect.Descriptor instead.
func (*RemoveNoteFromBoxRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveNoteFromBoxRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *RemoveNoteFromBoxRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

// Запрос на получение списка заметок в боксе
type ListBoxNotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// Параметры пагинации
	Pagination *v1.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Параметры сортировки
	Sort *v1.SortRequest `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// Фильтр по тегам заметок
	Tags          []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoxNotesRequest) Reset() {
	*x = ListBoxNotesRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoxNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoxNotesRequest) ProtoMessage() {}

func (x *ListBoxNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoxNotesRequest.ProtoReflect.Descriptor instead.
func (*ListBoxNotesRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListBoxNotesRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *ListBoxNotesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListBoxNotesRequest) GetSort() *v1.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListBoxNotesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Ответ со списком заметок в боксе
type ListBoxNotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список заметок
	Notes []*BoxNote `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	// Метаданные пагинации
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoxNotesResponse) Reset() {
	*x = ListBoxNotesResponse{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoxNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoxNotesResponse) ProtoMessage() {}

func (x *ListBoxNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoxNotesResponse.ProtoReflect.Descriptor instead.
func (*ListBoxNotesResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListBoxNotesResponse) GetNotes() []*BoxNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *ListBoxNotesResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Запрос на получение списка пользователей с доступом к боксу
type ListAccessUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса
	BoxId         string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessUsersRequest) Reset() {
	*x = ListAccessUsersRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessUsersRequest) ProtoMessage() {}

func (x *ListAccessUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessUsersRequest.ProtoReflect.Descriptor instead.
func (*ListAccessUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListAccessUsersRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

// Ответ со списком пользователей с доступом к боксу
type ListAccessUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список пользователей с доступом
	AccessUsers   []*AccessUser `protobuf:"bytes,1,rep,name=access_users,json=accessUsers,proto3" json:"access_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessUsersResponse) Reset() {
	*x = ListAccessUsersResponse{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessUsersResponse) ProtoMessage() {}

func (x *ListAccessUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessUsersResponse.ProtoReflect.Descriptor instead.
func (*ListAccessUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccessUsersResponse) GetAccessUsers() []*AccessUser {
	if x != nil {
		return x.AccessUsers
	}
	return nil
}

// Запрос на предоставление доступа к боксу другому пользователю
type GrantAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// Email пользователя, которому предоставляется доступ
	UserEmail string `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	// Уровень доступа
	AccessLevel AccessLevel `protobuf:"varint,3,opt,name=access_level,json=accessLevel,proto3,enum=notes.v1.AccessLevel" json:"access_level,omitempty"`
	// Персональное сообщение для пользователя (опционально)
	Message       *string `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAccessRequest) Reset() {
	*x = GrantAccessRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessRequest) ProtoMessage() {}

func (x *GrantAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{12}
}

func (x *GrantAccessRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *GrantAccessRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *GrantAccessRequest) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *GrantAccessRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Запрос на изменение уровня доступа к боксу
type UpdateAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// ID записи о доступе
	AccessId string `protobuf:"bytes,2,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	// Новый уровень доступа
	AccessLevel   AccessLevel `protobuf:"varint,3,opt,name=access_level,json=accessLevel,proto3,enum=notes.v1.AccessLevel" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccessRequest) Reset() {
	*x = UpdateAccessRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessRequest) ProtoMessage() {}

func (x *UpdateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAccessRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *UpdateAccessRequest) GetAccessId() string {
	if x != nil {
		return x.AccessId
	}
	return ""
}

func (x *UpdateAccessRequest) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

// Запрос на отзыв доступа к боксу
type RevokeAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// ID записи о доступе
	AccessId      string `protobuf:"bytes,2,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAccessRequest) Reset() {
	*x = RevokeAccessRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessRequest) ProtoMessage() {}

func (x *RevokeAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessRequest.ProtoReflect.Descriptor instead.
func (*RevokeAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeAccessRequest) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *RevokeAccessRequest) GetAccessId() string {
	if x != nil {
		return x.AccessId
	}
	return ""
}

// Структура бокса
type Box struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор бокса
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// ID пользователя, создавшего бокс
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Название бокса
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Описание бокса
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Тип бокса
	Type BoxType `protobuf:"varint,5,opt,name=type,proto3,enum=notes.v1.BoxType" json:"type,omitempty"`
	// Цвет бокса (HEX код)
	Color string `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	// Иконка бокса
	Icon string `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	// ID родительского бокса (если это вложенный бокс)
	ParentBoxId *string `protobuf:"bytes,8,opt,name=parent_box_id,json=parentBoxId,proto3,oneof" json:"parent_box_id,omitempty"`
	// Количество заметок в боксе
	NoteCount int32 `protobuf:"varint,9,opt,name=note_count,json=noteCount,proto3" json:"note_count,omitempty"`
	// Уровень доступа текущего пользователя к этому боксу
	CurrentUserAccessLevel AccessLevel `protobuf:"varint,10,opt,name=current_user_access_level,json=currentUserAccessLevel,proto3,enum=notes.v1.AccessLevel" json:"current_user_access_level,omitempty"`
	// Общие метаданные объекта
	Metadata *v1.Metadata `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Дополнительные метаданные
	CustomAttributes map[string]string `protobuf:"bytes,12,rep,name=custom_attributes,json=customAttributes,proto3" json:"custom_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Box) Reset() {
	*x = Box{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{15}
}

func (x *Box) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *Box) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Box) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Box) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Box) GetType() BoxType {
	if x != nil {
		return x.Type
	}
	return BoxType_BOX_TYPE_UNSPECIFIED
}

func (x *Box) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Box) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Box) GetParentBoxId() string {
	if x != nil && x.ParentBoxId != nil {
		return *x.ParentBoxId
	}
	return ""
}

func (x *Box) GetNoteCount() int32 {
	if x != nil {
		return x.NoteCount
	}
	return 0
}

func (x *Box) GetCurrentUserAccessLevel() AccessLevel {
	if x != nil {
		return x.CurrentUserAccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *Box) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Box) GetCustomAttributes() map[string]string {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

// Структура заметки в боксе (упрощенная версия заметки)
type BoxNote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID заметки
	NoteId string `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	// Заголовок заметки
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Предпросмотр содержимого заметки (обрезанный текст)
	Preview string `protobuf:"bytes,3,opt,name=preview,proto3" json:"preview,omitempty"`
	// Время добавления заметки в бокс
	AddedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxNote) Reset() {
	*x = BoxNote{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxNote) ProtoMessage() {}

func (x *BoxNote) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxNote.ProtoReflect.Descriptor instead.
func (*BoxNote) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{16}
}

func (x *BoxNote) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *BoxNote) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BoxNote) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *BoxNote) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

// Информация о доступе пользователя к боксу
type AccessUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID записи о доступе
	AccessId string `protobuf:"bytes,1,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	// ID пользователя
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Email пользователя
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Имя пользователя
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// Уровень доступа
	AccessLevel AccessLevel `protobuf:"varint,5,opt,name=access_level,json=accessLevel,proto3,enum=notes.v1.AccessLevel" json:"access_level,omitempty"`
	// Время предоставления доступа
	GrantedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	// Время последнего изменения доступа
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessUser) Reset() {
	*x = AccessUser{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessUser) ProtoMessage() {}

func (x *AccessUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessUser.ProtoReflect.Descriptor instead.
func (*AccessUser) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{17}
}

func (x *AccessUser) GetAccessId() string {
	if x != nil {
		return x.AccessId
	}
	return ""
}

func (x *AccessUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccessUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccessUser) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *AccessUser) GetGrantedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GrantedAt
	}
	return nil
}

func (x *AccessUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Ответ с информацией о боксе
type BoxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Бокс
	Box           *Box `protobuf:"bytes,1,opt,name=box,proto3" json:"box,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxResponse) Reset() {
	*x = BoxResponse{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxResponse) ProtoMessage() {}

func (x *BoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxResponse.ProtoReflect.Descriptor instead.
func (*BoxResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{18}
}

func (x *BoxResponse) GetBox() *Box {
	if x != nil {
		return x.Box
	}
	return nil
}

// Ответ на добавление заметки в бокс
type BoxNoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бокса
	BoxId string `protobuf:"bytes,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// ID заметки
	NoteId string `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	// Статус операции
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxNoteResponse) Reset() {
	*x = BoxNoteResponse{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxNoteResponse) ProtoMessage() {}

func (x *BoxNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxNoteResponse.ProtoReflect.Descriptor instead.
func (*BoxNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{19}
}

func (x *BoxNoteResponse) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *BoxNoteResponse) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *BoxNoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Ответ с информацией о доступе
type AccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация о предоставленном доступе
	Access        *AccessUser `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessResponse) Reset() {
	*x = AccessResponse{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessResponse) ProtoMessage() {}

func (x *AccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessResponse.ProtoReflect.Descriptor instead.
func (*AccessResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{20}
}

func (x *AccessResponse) GetAccess() *AccessUser {
	if x != nil {
		return x.Access
	}
	return nil
}

// Запрос на получение ошибки сервиса боксов
type GetBoxErrorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Код ошибки
	ErrorCode v1.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.v1.ErrorCode" json:"error_code,omitempty"`
	// Дополнительные параметры для форматирования сообщения об ошибке
	Params        map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoxErrorRequest) Reset() {
	*x = GetBoxErrorRequest{}
	mi := &file_api_notes_v1_box_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoxErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoxErrorRequest) ProtoMessage() {}

func (x *GetBoxErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_box_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoxErrorRequest.ProtoReflect.Descriptor instead.
func (*GetBoxErrorRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_box_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetBoxErrorRequest) GetErrorCode() v1.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return v1.ErrorCode(0)
}

func (x *GetBoxErrorRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_api_notes_v1_box_service_proto protoreflect.FileDescriptor

const file_api_notes_v1_box_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/notes/v1/box_service.proto\x12\bnotes.v1\x1a api/google/api/annotations.proto\x1a#api/google/protobuf/timestamp.proto\x1a\x1fapi/google/protobuf/empty.proto\x1a\x1eapi/common/v1/pagination.proto\x1a\x1capi/common/v1/metadata.proto\x1a\x1aapi/common/v1/errors.proto\"\xf1\x03\n" +
	"\x10CreateBoxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x01R\x05color\x88\x01\x01\x12'\n" +
	"\rparent_box_id\x18\x04 \x01(\tH\x02R\vparentBoxId\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x05 \x01(\tH\x03R\x04icon\x88\x01\x01\x12D\n" +
	"\bmetadata\x18\x06 \x03(\v2(.notes.v1.CreateBoxRequest.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1f\n" +
	"\bpriority\x18\b \x01(\x05H\x04R\bpriority\x88\x01\x01\x12K\n" +
	"\x13user_defined_fields\x18\t \x03(\v2\x1b.common.v1.UserDefinedFieldR\x11userDefinedFields\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_colorB\x10\n" +
	"\x0e_parent_box_idB\a\n" +
	"\x05_iconB\v\n" +
	"\t_priority\"&\n" +
	"\rGetBoxRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\"\x93\x02\n" +
	"\x10ListBoxesRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.notes.v1.BoxTypeH\x00R\x04type\x88\x01\x01\x12'\n" +
	"\rparent_box_id\x18\x03 \x01(\tH\x01R\vparentBoxId\x88\x01\x01\x12%\n" +
	"\x0einclude_shared\x18\x04 \x01(\bR\rincludeShared\x12*\n" +
	"\x04sort\x18\x05 \x01(\v2\x16.common.v1.SortRequestR\x04sortB\a\n" +
	"\x05_typeB\x10\n" +
	"\x0e_parent_box_id\"w\n" +
	"\x11ListBoxesResponse\x12#\n" +
	"\x05boxes\x18\x01 \x03(\v2\r.notes.v1.BoxR\x05boxes\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\"\x87\x03\n" +
	"\x10UpdateBoxRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x04 \x01(\tH\x02R\x05color\x88\x01\x01\x12'\n" +
	"\rparent_box_id\x18\x05 \x01(\tH\x03R\vparentBoxId\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x06 \x01(\tH\x04R\x04icon\x88\x01\x01\x12D\n" +
	"\bmetadata\x18\a \x03(\v2(.notes.v1.UpdateBoxRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_colorB\x10\n" +
	"\x0e_parent_box_idB\a\n" +
	"\x05_icon\"R\n" +
	"\x10DeleteBoxRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12'\n" +
	"\x0fdelete_contents\x18\x02 \x01(\bR\x0edeleteContents\"E\n" +
	"\x13AddNoteToBoxRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\"J\n" +
	"\x18RemoveNoteFromBoxRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\"\xaa\x01\n" +
	"\x13ListBoxNotesRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12*\n" +
	"\x04sort\x18\x03 \x01(\v2\x16.common.v1.SortRequestR\x04sort\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"~\n" +
	"\x14ListBoxNotesResponse\x12'\n" +
	"\x05notes\x18\x01 \x03(\v2\x11.notes.v1.BoxNoteR\x05notes\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\"/\n" +
	"\x16ListAccessUsersRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\"R\n" +
	"\x17ListAccessUsersResponse\x127\n" +
	"\faccess_users\x18\x01 \x03(\v2\x14.notes.v1.AccessUserR\vaccessUsers\"\xaf\x01\n" +
	"\x12GrantAccessRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x128\n" +
	"\faccess_level\x18\x03 \x01(\x0e2\x15.notes.v1.AccessLevelR\vaccessLevel\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\x83\x01\n" +
	"\x13UpdateAccessRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x1b\n" +
	"\taccess_id\x18\x02 \x01(\tR\baccessId\x128\n" +
	"\faccess_level\x18\x03 \x01(\x0e2\x15.notes.v1.AccessLevelR\vaccessLevel\"I\n" +
	"\x13RevokeAccessRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x1b\n" +
	"\taccess_id\x18\x02 \x01(\tR\baccessId\"\xb0\x04\n" +
	"\x03Box\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12%\n" +
	"\x04type\x18\x05 \x01(\x0e2\x11.notes.v1.BoxTypeR\x04type\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12'\n" +
	"\rparent_box_id\x18\b \x01(\tH\x00R\vparentBoxId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"note_count\x18\t \x01(\x05R\tnoteCount\x12P\n" +
	"\x19current_user_access_level\x18\n" +
	" \x01(\x0e2\x15.notes.v1.AccessLevelR\x16currentUserAccessLevel\x12/\n" +
	"\bmetadata\x18\v \x01(\v2\x13.common.v1.MetadataR\bmetadata\x12P\n" +
	"\x11custom_attributes\x18\f \x03(\v2#.notes.v1.Box.CustomAttributesEntryR\x10customAttributes\x1aC\n" +
	"\x15CustomAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_parent_box_id\"\x89\x01\n" +
	"\aBoxNote\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\apreview\x18\x03 \x01(\tR\apreview\x125\n" +
	"\badded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\"\xa4\x02\n" +
	"\n" +
	"AccessUser\x12\x1b\n" +
	"\taccess_id\x18\x01 \x01(\tR\baccessId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x128\n" +
	"\faccess_level\x18\x05 \x01(\x0e2\x15.notes.v1.AccessLevelR\vaccessLevel\x129\n" +
	"\n" +
	"granted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tgrantedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\".\n" +
	"\vBoxResponse\x12\x1f\n" +
	"\x03box\x18\x01 \x01(\v2\r.notes.v1.BoxR\x03box\"[\n" +
	"\x0fBoxNoteResponse\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\tR\x05boxId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\">\n" +
	"\x0eAccessResponse\x12,\n" +
	"\x06access\x18\x01 \x01(\v2\x14.notes.v1.AccessUserR\x06access\"\xc6\x01\n" +
	"\x12GetBoxErrorRequest\x123\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x14.common.v1.ErrorCodeR\terrorCode\x12@\n" +
	"\x06params\x18\x02 \x03(\v2(.notes.v1.GetBoxErrorRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*r\n" +
	"\vAccessLevel\x12\x1c\n" +
	"\x18ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACCESS_LEVEL_READ\x10\x01\x12\x16\n" +
	"\x12ACCESS_LEVEL_WRITE\x10\x02\x12\x16\n" +
	"\x12ACCESS_LEVEL_ADMIN\x10\x03*v\n" +
	"\aBoxType\x12\x18\n" +
	"\x14BOX_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BOX_TYPE_REGULAR\x10\x01\x12\x11\n" +
	"\rBOX_TYPE_ROOT\x10\x02\x12\x13\n" +
	"\x0fBOX_TYPE_SYSTEM\x10\x03\x12\x13\n" +
	"\x0fBOX_TYPE_SHARED\x10\x042\xd4\n" +
	"\n" +
	"\n" +
	"BoxService\x12T\n" +
	"\tCreateBox\x12\x1a.notes.v1.CreateBoxRequest\x1a\x15.notes.v1.BoxResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/boxes\x12T\n" +
	"\x06GetBox\x12\x17.notes.v1.GetBoxRequest\x1a\x15.notes.v1.BoxResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/boxes/{box_id}\x12W\n" +
	"\tListBoxes\x12\x1a.notes.v1.ListBoxesRequest\x1a\x1b.notes.v1.ListBoxesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/boxes\x12]\n" +
	"\tUpdateBox\x12\x1a.notes.v1.UpdateBoxRequest\x1a\x15.notes.v1.BoxResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*2\x12/v1/boxes/{box_id}\x12[\n" +
	"\tDeleteBox\x12\x1a.notes.v1.DeleteBoxRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/boxes/{box_id}\x12m\n" +
	"\fAddNoteToBox\x12\x1d.notes.v1.AddNoteToBoxRequest\x1a\x19.notes.v1.BoxNoteResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/boxes/{box_id}/notes\x12{\n" +
	"\x11RemoveNoteFromBox\x12\".notes.v1.RemoveNoteFromBoxRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$*\"/v1/boxes/{box_id}/notes/{note_id}\x12o\n" +
	"\fListBoxNotes\x12\x1d.notes.v1.ListBoxNotesRequest\x1a\x1e.notes.v1.ListBoxNotesResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/boxes/{box_id}/notes\x12{\n" +
	"\x0fListAccessUsers\x12 .notes.v1.ListAccessUsersRequest\x1a!.notes.v1.ListAccessUsersResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/boxes/{box_id}/accesses\x12m\n" +
	"\vGrantAccess\x12\x1c.notes.v1.GrantAccessRequest\x1a\x18.notes.v1.AccessResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/boxes/{box_id}/accesses\x12{\n" +
	"\fUpdateAccess\x12\x1d.notes.v1.UpdateAccessRequest\x1a\x18.notes.v1.AccessResponse\"2\x82\xd3\xe4\x93\x02,:\x01*2'/v1/boxes/{box_id}/accesses/{access_id}\x12v\n" +
	"\fRevokeAccess\x12\x1d.notes.v1.RevokeAccessRequest\x1a\x16.google.protobuf.Empty\"/\x82\xd3\xe4\x93\x02)*'/v1/boxes/{box_id}/accesses/{access_id}\x12G\n" +
	"\vGetBoxError\x12\x1c.notes.v1.GetBoxErrorRequest\x1a\x18.common.v1.ErrorResponse\"\x00B\\ZZgitlab.crja72.ru/golang/2025/spring/course/projects/go9/gogetnote/pkg/api/notes/v1;notesv1b\x06proto3"

var (
	file_api_notes_v1_box_service_proto_rawDescOnce sync.Once
	file_api_notes_v1_box_service_proto_rawDescData []byte
)

func file_api_notes_v1_box_service_proto_rawDescGZIP() []byte {
	file_api_notes_v1_box_service_proto_rawDescOnce.Do(func() {
		file_api_notes_v1_box_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_v1_box_service_proto_rawDesc), len(file_api_notes_v1_box_service_proto_rawDesc)))
	})
	return file_api_notes_v1_box_service_proto_rawDescData
}

var file_api_notes_v1_box_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_notes_v1_box_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_notes_v1_box_service_proto_goTypes = []any{
	(AccessLevel)(0),                 // 0: notes.v1.AccessLevel
	(BoxType)(0),                     // 1: notes.v1.BoxType
	(*CreateBoxRequest)(nil),         // 2: notes.v1.CreateBoxRequest
	(*GetBoxRequest)(nil),            // 3: notes.v1.GetBoxRequest
	(*ListBoxesRequest)(nil),         // 4: notes.v1.ListBoxesRequest
	(*ListBoxesResponse)(nil),        // 5: notes.v1.ListBoxesResponse
	(*UpdateBoxRequest)(nil),         // 6: notes.v1.UpdateBoxRequest
	(*DeleteBoxRequest)(nil),         // 7: notes.v1.DeleteBoxRequest
	(*AddNoteToBoxRequest)(nil),      // 8: notes.v1.AddNoteToBoxRequest
	(*RemoveNoteFromBoxRequest)(nil), // 9: notes.v1.RemoveNoteFromBoxRequest
	(*ListBoxNotesRequest)(nil),      // 10: notes.v1.ListBoxNotesRequest
	(*ListBoxNotesResponse)(nil),     // 11: notes.v1.ListBoxNotesResponse
	(*ListAccessUsersRequest)(nil),   // 12: notes.v1.ListAccessUsersRequest
	(*ListAccessUsersResponse)(nil),  // 13: notes.v1.ListAccessUsersResponse
	(*GrantAccessRequest)(nil),       // 14: notes.v1.GrantAccessRequest
	(*UpdateAccessRequest)(nil),      // 15: notes.v1.UpdateAccessRequest
	(*RevokeAccessRequest)(nil),      // 16: notes.v1.RevokeAccessRequest
	(*Box)(nil),                      // 17: notes.v1.Box
	(*BoxNote)(nil),                  // 18: notes.v1.BoxNote
	(*AccessUser)(nil),               // 19: notes.v1.AccessUser
	(*BoxResponse)(nil),              // 20: notes.v1.BoxResponse
	(*BoxNoteResponse)(nil),          // 21: notes.v1.BoxNoteResponse
	(*AccessResponse)(nil),           // 22: notes.v1.AccessResponse
	(*GetBoxErrorRequest)(nil),       // 23: notes.v1.GetBoxErrorRequest
	nil,                              // 24: notes.v1.CreateBoxRequest.MetadataEntry
	nil,                              // 25: notes.v1.UpdateBoxRequest.MetadataEntry
	nil,                              // 26: notes.v1.Box.CustomAttributesEntry
	nil,                              // 27: notes.v1.GetBoxErrorRequest.ParamsEntry
	(*v1.UserDefinedField)(nil),      // 28: common.v1.UserDefinedField
	(*v1.PaginationRequest)(nil),     // 29: common.v1.PaginationRequest
	(*v1.SortRequest)(nil),           // 30: common.v1.SortRequest
	(*v1.PaginationResponse)(nil),    // 31: common.v1.PaginationResponse
	(*v1.Metadata)(nil),              // 32: common.v1.Metadata
	(*timestamppb.Timestamp)(nil),    // 33: google.protobuf.Timestamp
	(v1.ErrorCode)(0),                // 34: common.v1.ErrorCode
	(*emptypb.Empty)(nil),            // 35: google.protobuf.Empty
	(*v1.ErrorResponse)(nil),         // 36: common.v1.ErrorResponse
}
var file_api_notes_v1_box_service_proto_depIdxs = []int32{
	24, // 0: notes.v1.CreateBoxRequest.metadata:type_name -> notes.v1.CreateBoxRequest.MetadataEntry
	28, // 1: notes.v1.CreateBoxRequest.user_defined_fields:type_name -> common.v1.UserDefinedField
	29, // 2: notes.v1.ListBoxesRequest.pagination:type_name -> common.v1.PaginationRequest
	1,  // 3: notes.v1.ListBoxesRequest.type:type_name -> notes.v1.BoxType
	30, // 4: notes.v1.ListBoxesRequest.sort:type_name -> common.v1.SortRequest
	17, // 5: notes.v1.ListBoxesResponse.boxes:type_name -> notes.v1.Box
	31, // 6: notes.v1.ListBoxesResponse.pagination:type_name -> common.v1.PaginationResponse
	25, // 7: notes.v1.UpdateBoxRequest.metadata:type_name -> notes.v1.UpdateBoxRequest.MetadataEntry
	29, // 8: notes.v1.ListBoxNotesRequest.pagination:type_name -> common.v1.PaginationRequest
	30, // 9: notes.v1.ListBoxNotesRequest.sort:type_name -> common.v1.SortRequest
	18, // 10: notes.v1.ListBoxNotesResponse.notes:type_name -> notes.v1.BoxNote
	31, // 11: notes.v1.ListBoxNotesResponse.pagination:type_name -> common.v1.PaginationResponse
	19, // 12: notes.v1.ListAccessUsersResponse.access_users:type_name -> notes.v1.AccessUser
	0,  // 13: notes.v1.GrantAccessRequest.access_level:type_name -> notes.v1.AccessLevel
	0,  // 14: notes.v1.UpdateAccessRequest.access_level:type_name -> notes.v1.AccessLevel
	1,  // 15: notes.v1.Box.type:type_name -> notes.v1.BoxType
	0,  // 16: notes.v1.Box.current_user_access_level:type_name -> notes.v1.AccessLevel
	32, // 17: notes.v1.Box.metadata:type_name -> common.v1.Metadata
	26, // 18: notes.v1.Box.custom_attributes:type_name -> notes.v1.Box.CustomAttributesEntry
	33, // 19: notes.v1.BoxNote.added_at:type_name -> google.protobuf.Timestamp
	0,  // 20: notes.v1.AccessUser.access_level:type_name -> notes.v1.AccessLevel
	33, // 21: notes.v1.AccessUser.granted_at:type_name -> google.protobuf.Timestamp
	33, // 22: notes.v1.AccessUser.updated_at:type_name -> google.protobuf.Timestamp
	17, // 23: notes.v1.BoxResponse.box:type_name -> notes.v1.Box
	19, // 24: notes.v1.AccessResponse.access:type_name -> notes.v1.AccessUser
	34, // 25: notes.v1.GetBoxErrorRequest.error_code:type_name -> common.v1.ErrorCode
	27, // 26: notes.v1.GetBoxErrorRequest.params:type_name -> notes.v1.GetBoxErrorRequest.ParamsEntry
	2,  // 27: notes.v1.BoxService.CreateBox:input_type -> notes.v1.CreateBoxRequest
	3,  // 28: notes.v1.BoxService.GetBox:input_type -> notes.v1.GetBoxRequest
	4,  // 29: notes.v1.BoxService.ListBoxes:input_type -> notes.v1.ListBoxesRequest
	6,  // 30: notes.v1.BoxService.UpdateBox:input_type -> notes.v1.UpdateBoxRequest
	7,  // 31: notes.v1.BoxService.DeleteBox:input_type -> notes.v1.DeleteBoxRequest
	8,  // 32: notes.v1.BoxService.AddNoteToBox:input_type -> notes.v1.AddNoteToBoxRequest
	9,  // 33: notes.v1.BoxService.RemoveNoteFromBox:input_type -> notes.v1.RemoveNoteFromBoxRequest
	10, // 34: notes.v1.BoxService.ListBoxNotes:input_type -> notes.v1.ListBoxNotesRequest
	12, // 35: notes.v1.BoxService.ListAccessUsers:input_type -> notes.v1.ListAccessUsersRequest
	14, // 36: notes.v1.BoxService.GrantAccess:input_type -> notes.v1.GrantAccessRequest
	15, // 37: notes.v1.BoxService.UpdateAccess:input_type -> notes.v1.UpdateAccessRequest
	16, // 38: notes.v1.BoxService.RevokeAccess:input_type -> notes.v1.RevokeAccessRequest
	23, // 39: notes.v1.BoxService.GetBoxError:input_type -> notes.v1.GetBoxErrorRequest
	20, // 40: notes.v1.BoxService.CreateBox:output_type -> notes.v1.BoxResponse
	20, // 41: notes.v1.BoxService.GetBox:output_type -> notes.v1.BoxResponse
	5,  // 42: notes.v1.BoxService.ListBoxes:output_type -> notes.v1.ListBoxesResponse
	20, // 43: notes.v1.BoxService.UpdateBox:output_type -> notes.v1.BoxResponse
	35, // 44: notes.v1.BoxService.DeleteBox:output_type -> google.protobuf.Empty
	21, // 45: notes.v1.BoxService.AddNoteToBox:output_type -> notes.v1.BoxNoteResponse
	35, // 46: notes.v1.BoxService.RemoveNoteFromBox:output_type -> google.protobuf.Empty
	11, // 47: notes.v1.BoxService.ListBoxNotes:output_type -> notes.v1.ListBoxNotesResponse
	13, // 48: notes.v1.BoxService.ListAccessUsers:output_type -> notes.v1.ListAccessUsersResponse
	22, // 49: notes.v1.BoxService.GrantAccess:output_type -> notes.v1.AccessResponse
	22, // 50: notes.v1.BoxService.UpdateAccess:output_type -> notes.v1.AccessResponse
	35, // 51: notes.v1.BoxService.RevokeAccess:output_type -> google.protobuf.Empty
	36, // 52: notes.v1.BoxService.GetBoxError:output_type -> common.v1.ErrorResponse
	40, // [40:53] is the sub-list for method output_type
	27, // [27:40] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_api_notes_v1_box_service_proto_init() }
func file_api_notes_v1_box_service_proto_init() {
	if File_api_notes_v1_box_service_proto != nil {
		return
	}
	file_api_notes_v1_box_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_notes_v1_box_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_notes_v1_box_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_notes_v1_box_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_notes_v1_box_service_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_box_service_proto_rawDesc), len(file_api_notes_v1_box_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notes_v1_box_service_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_box_service_proto_depIdxs,
		EnumInfos:         file_api_notes_v1_box_service_proto_enumTypes,
		MessageInfos:      file_api_notes_v1_box_service_proto_msgTypes,
	}.Build()
	File_api_notes_v1_box_service_proto = out.File
	file_api_notes_v1_box_service_proto_goTypes = nil
	file_api_notes_v1_box_service_proto_depIdxs = nil
}
